### ISSUE TITLE
About function `get_vac_top_list`

### ISSUE THREAD

**Issue by Fenyutanchan** [zhaoli-IHEP/FeAmGen.jl#16]
At https://github.com/zhaoli-IHEP/FeAmGen.jl/blob/fb1e70b8aebe8d008cc03184f56266e6925d4f75/src/Integral.jl#LL378-L392
```julia
##################################
function get_vac_top_list(
    vac_den_list::Vector{Basic}
)::Vector{ Vector{Basic} }
##################################

  n_den = length(vac_den_list)
  vac_mom_list = map( first∘get_args, vac_den_list )
  unique_vac_mom_list = unique(vac_mom_list )
  ...
```
Maybe `unique(abs, vac_mom_list)` better?

At https://github.com/zhaoli-IHEP/FeAmGen.jl/blob/fb1e70b8aebe8d008cc03184f56266e6925d4f75/src/Integral.jl#LL394
```julia
  ...
  pos_list = findall( x->count(==(x),vac_mom_list)==2, unique_vac_mom_list )
  ...
```
Why do we only count two times here?

**Comment by zhaoli-IHEP** [comment]
It is assumed the loop momenta has been transformed into canonical form. There is no need to use `abs`. 
And there are only two cases, one has `im`, the other does not.
